### ISSUE TITLE
Version 2.0.4 not working \kartik\datecontrol\DateControl

### ISSUE THREAD

**Issue by smartycoder** [yiisoft/yii2-bootstrap5#60]
### Steps to reproduce the problem:
If \kartik\datecontrol\DateControl is installed with version 2.0.4 - JavaScript error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')`

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.45
| PHP version      |8.1
| Operating system |Linux

**Comment by simialbi** [comment]
Do you have a stacktrace?

**Comment by newadventure079** [comment]
I'm seeing something similar also using a kartik widget

```
jquery.js:4059 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'nextElementSibling')
    at Object.next (selector-engine.js:63:24)
    at Dropdown._getMenuElement (dropdown.js:270:27)
    at new Dropdown (dropdown.js:103:23)
    at HTMLDocument.<anonymous> (user-preferences:250:2)
    at mightThrow (jquery.js:3766:29)
    at process (jquery.js:3834:12)
```

**Comment by smartycoder** [comment]
@simialbi 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')
    at new Dropdown (dropdown.js:97:34)
    at HTMLDocument.<anonymous>
    at mightThrow (jquery.js:3766:29)
    at process (jquery.js:3834:12)
```
